version: "3"
services:
  springbootapp:
    image: springbootapp:latest
    container_name: springbootapp
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/spring_boot_db
    expose:
      - 8080
    ports:
      - 8080:8080
    restart: unless-stopped
    depends_on:
      - postgres
    links:
      - postgres
    networks:
      - my_network
  postgres:
    image: postgres:latest
    container_name: postgres
    volumes:
      - postgres-data:/var/lib/postgresql/data
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: spring_boot_db
    networks:
      - my_network
    restart: unless-stopped
volumes:
  postgres-data:

networks:
  my_network:
    driver: bridge